DEFAULT_DISTRIBUTED_DOWNLOADED_TARFILE = ".dparts.tgz"
DEFAULT_PARTS_LIST_FILE_NAME = ".dparts"
NS = 1000000000  # S
REPORT_FREQUENCY = int(0.5 * NS)  # 0.5S
SLICING = True
THREADED = True
# CHUNK_SIZE = 1 << 16
CHUNK_SIZE = 1 << 10
